### ISSUE TITLE
run script error

### ISSUE THREAD

**Issue by luutuankiet** [gleitz/alfred-howdoi#2]
Hi, I have both howdoi installed by brew and the howdoi alfred workflow installed. howdoi worked fine from the terminal, but nothing showed up on the alfred workflow bar. Here's the debug message I got :

`ERROR: Howdoi[Run Script] /Users/luutuankiet/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/B4A6800E-3067-4C83-B28E-6786F62FCD0B: line 1: howdoi: No such file or directory`

Happy to provide more info. I am on m1, ventura 13.2.1

**Comment by gleitz** [comment]
I ran into this issue as well. It's because I was using a custom path for my homebrew installation. 
Would you run `which howdoi` and let me know where it's installed?
Alfred uses a known set of folders to look for executables. A fix would be to edit the workflow to use the full path to howdoi, or to set a custom PATH variable for Alfred so it knows where to look.

**Comment by gleitz** [comment]
Here's more info about what Alfred is doing and the possible fixes.
https://github.com/gleitz/alfred-howdoi/pull/1#issuecomment-1404063232

**Comment by luutuankiet** [comment]
thanks for the info, took me awhile to wrap my head around my howdoi brew installation and config scripts in alfred; changed the script to use the full howdoi executable path worked.
